# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19

      - name: Build
        run: go build -v ./...

      - name: Test
        if: github.event_name == 'push'
        env:
          STRIPE_SK: ${{ secrets.STRIPE_SK }}
          STRIPE_WH: ${{ secrets.STRIPE_WH }}
          CURRENCY: ${{ secrets.CURRENCY }}
          DESTINATION: ${{ secrets.DESTINATION }}
          BALANCE_TRANSACTION_ID: ${{ secrets.BALANCE_TRANSACTION_ID }}
        run: go test -v -cover -coverprofile=coverage.txt -covermode=atomic ./...

      - name: Upload coverage to Codecov
        if: github.event_name == 'push'
        run: bash <(curl -s https://codecov.io/bash)
